@host = https://localhost:5050

### Ping
GET {{host}}/ping
Accept: application/json

### Dev unlock (Development only)
POST {{host}}/governance/unlock/dev
Content-Type: application/json

{
  "minutes": 15
}

### Device info
GET {{host}}/getDeviceInfo
Accept: application/json

### Mnemonic (requires unlock)
GET {{host}}/getMnemonic
Accept: application/json

###
